#!/bin/bash 
export WORKSPACE=${WORKSPACE:-${BASH_SOURCE%/*}}
export CFG_PREFIX=sshd-ingress-local-forward-$LOGNAME-$(printf "%(%s)T" -1)
export DOCKER_IMAGE=${DOCKER_IMAGE:-local/network/sshd:latest}
export SSHD_AUTHORIZED_KEYS_DIR=${SSHD_AUTHORIZED_KEYS_DIR:-~/.ingress_sshd_keys/}
export SSHD_INTERNAL_FORWARDING_PORT_01=${SSHD_INTERNAL_FORWARDING_PORT_01?Need SSHD_INTERNAL_FORWARDING_PORT_01}
export SSHD_EXTERNAL_FORWARDING_PORT_01=${SSHD_EXTERNAL_FORWARDING_PORT_01:-$SSHD_INTERNAL_FORWARDING_PORT_01}
export SSHD_INTERNAL_FORWARDING_PORT_02=${SSHD_INTERNAL_FORWARDING_PORT_02?Need SSHD_INTERNAL_FORWARDING_PORT_02}
export SSHD_EXTERNAL_FORWARDING_PORT_02=${SSHD_EXTERNAL_FORWARDING_PORT_02:-$SSHD_INTERNAL_FORWARDING_PORT_02}
export SSHD_IPV6_SUBNET=${SSHD_IPV6_SUBNET?Need SSHD_IPV6_SUBNET (e.g. 2001:db8:c::2:0/120)}
export SSHD_IPV6_GATEWAY=${SSHD_IPV6_GATEWAY?Need SSHD_IPV6_GATEWAY (e.g. 2001:db8:c::2:1)}
export SSHD_IPV6_ADDRESS=${SSHD_IPV6_ADDRESS?Need SSHD_IPV6_ADDRESS (e.g. 2001:db8:c::2:2)}
cd $WORKSPACE || exit $?
docker buildx bake local
docker compose up -d
