#!/bin/bash 
export WORKSPACE=${WORKSPACE:-${BASH_SOURCE%/*}}
export APP_NAME=${APP_NAME:-sshd}
export STACK_NAME=${STACK_NAME:-$APP_NAME}
printf -v now "%(%s)T" -1
export CFG_PREFIX=$STACK_NAME-$now
export STACK_CONFIG=${STACK_CONFIG:-$WORKSPACE}
export STACK_CERTS=${STACK_CERTS:-$WORKSPACE}
export REGISTRY_HTTP_SECRET=${REGISTRY_HTTP_SECRET:-$(uuidgen)}
export DOCKER_IMAGE=${DOCKER_IMAGE:-local/network/sshd:latest}
export SSHD_EXTERNAL_INGRESS_PORT=${SSHD_EXTERNAL_INGRESS_PORT?Need SSHD_EXTERNAL_INGRESS_PORT}
export SSHD_INTERNAL_FORWARDING_PORT_01=${SSHD_INTERNAL_FORWARDING_PORT_01?Need SSHD_INTERNAL_FORWARDING_PORT_01}
export SSHD_EXTERNAL_FORWARDING_PORT_01=${SSHD_EXTERNAL_FORWARDING_PORT_01:-$SSHD_INTERNAL_FORWARDING_PORT_01}
export SSHD_INTERNAL_FORWARDING_PORT_02=${SSHD_INTERNAL_FORWARDING_PORT_02?Need SSHD_INTERNAL_FORWARDING_PORT_02}
export SSHD_EXTERNAL_FORWARDING_PORT_02=${SSHD_EXTERNAL_FORWARDING_PORT_02:-$SSHD_INTERNAL_FORWARDING_PORT_02}
cd $WORKSPACE || exit $?
docker buildx bake local
docker stack deploy \
    -c $WORKSPACE/$APP_NAME.yml \
    --with-registry-auth \
    --detach=false \
    $STACK_NAME
