services:
  sshd:
    image: ${DOCKER_IMAGE:-local/network/sshd:latest}
    container_name: sshd-ingress-local-forward-${LOGNAME}
    restart: always
    tmpfs:
      - /tmp:size=1M
      - /var/tmp:size=1M
      - /run:size=1M
    cap_add:
      - ALL
      - NET_ADMIN
    cap_drop:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    memswap_limit: 128m
    pids_limit: 100
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    networks:
      - dmz
    ports:
      - "0.0.0.0:${SSHD_EXTERNAL_INGRESS_PORT}:2222"
      - "[::]:${SSHD_EXTERNAL_INGRESS_PORT}:2222"
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_01}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_01:-$SSHD_INTERNAL_FORWARDING_PORT_01}"
        protocol: tcp
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_02}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_02:-$SSHD_INTERNAL_FORWARDING_PORT_02}"
        protocol: tcp
    volumes:
      - ssh-known-hosts:/sshd/known_hosts
      - ssh-host-keys:/sshd/host_keys
      - type: bind
        source: "${SSHD_AUTHORIZED_KEYS_DIR}"
        target: /sshd/authorized_keys
        read_only: true

networks:
  dmz:
    driver: bridge
    enable_ipv6: true

volumes:
  ssh-known-hosts:
  ssh-host-keys:
  ssh-etc:
