services:
  sshd:
    image: ${DOCKER_IMAGE:-local/network/sshd:latest}
    container_name: sshd-ingress-local-forward-${LOGNAME}
    restart: always
    tmpfs:
      - /tmp:size=1M
      - /var/tmp:size=1M
      - /run:size=1M
      - /var/empty:size=1M
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CAP_SYS_CHROOT
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    memswap_limit: 128m
    pids_limit: 100
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    networks:
      - dmz-ipv6
      - dmz-ipv4
    ports:
      # IPv4 is nat on bridge, so we have an extra mapping
      - "0.0.0.0:22322:22322"
      # IPv6 is routed on bridge, so available
      # - "[::]:22322:22322"
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_01}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_01:-$SSHD_INTERNAL_FORWARDING_PORT_01}"
        protocol: tcp
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_02}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_02:-$SSHD_INTERNAL_FORWARDING_PORT_02}"
        protocol: tcp
    volumes:
      - ssh-known-hosts:/sshd/known_hosts
      - ssh-host-keys:/sshd/host_keys
      - type: bind
        source: "${SSHD_AUTHORIZED_KEYS_DIR}"
        target: /sshd/authorized_keys
        read_only: true

networks:
  dmz-ipv6:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: "routed"
    ipam:
      driver: default
      config:
        - subnet: 2a02:a03f:8789:e700:c::/120
          gateway: 2a02:a03f:8789:e700:c::1
  dmz-ipv4:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: "nat"
      com.docker.network.bridge.enable_ip_masquerade: "true"  # Crucial to let NAT forward traffic back out
      com.docker.network.bridge.inhibit_ipv4: "false"         # Ensures IPv4 isn't blocked on this bridge
    ipam:
      driver: default
      config:
        - subnet: 10.99.1.0/24

volumes:
  ssh-known-hosts:
  ssh-host-keys:
