version: '3.8'

x-common-deploy: &common-deploy
  mode: global
  update_config:
    delay: 0s
    order: stop-first
    failure_action: continue
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 5
    window: 120s

x-deploy: &deploy
  deploy:
    <<: *common-deploy
    placement:
      constraints:
        - node.labels.${APP_NAME}==1

services:
  sshd:
    <<: *deploy
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${APP_NAME}-sshd:latest
    hostname: "sshd"
    networks:
      - sshdipv4
    ports:
      - target: 22
        published: "${SSHD_EXTERNAL_INGRESS_PORT}"
        protocol: tcp
        mode: ingress
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_01}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_01}"
        protocol: tcp
        mode: ingress
      - target: "${SSHD_INTERNAL_FORWARDING_PORT_02}"
        published: "${SSHD_EXTERNAL_FORWARDING_PORT_02}"
        protocol: tcp
        mode: ingress
    volumes:
      - ssh-known-hosts:/sshd/known_hosts
      - ssh-host-keys:/sshd/host_keys
      - ssh-authorized-keys:/sshd/authorized_keys

networks:
  sshdipv4:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "1"
      gateway: 10.10.1.1
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/28

volumes:
  ssh-known-hosts:
    name: app-${APP_NAME}-ssh-known-hosts
  ssh-host-keys:
    name: app-${APP_NAME}-ssh-host-keys
  ssh-authorized-keys:
    name: app-${APP_NAME}-ssh-authorized-keys
    driver: local
    driver_opts:
      type: none
      device: /mnt/ssd/docker-sshd/authorized-keys
      o: bind
